### ISSUE TITLE
How can I change language?

### ISSUE THREAD

**Issue by jameszasod** [AppDevGuy/OSSSpeechKit#27] opened 2020-10-08 06:53 UTC
How can I switch language when engine is running?

This is my code
<img width="652" alt="Screen Shot 2563-10-08 at 13 52 57" src="https://user-images.githubusercontent.com/13145084/95424890-9b81ea80-096d-11eb-84ed-2e0c84ec1652.png">

Thank!!

**Comment by AppDevGuy** [comment] 2020-10-08 07:12
What you have above is correct. When you select `recordVoice()` that will apply the latest voice settings.

**Comment by jameszasod** [comment] 2020-10-08 07:17
My app is crash when I change it
<img width="1062" alt="Screen Shot 2563-10-08 at 14 16 18" src="https://user-images.githubusercontent.com/13145084/95426886-e3564100-0970-11eb-8ed9-01f900a3e208.png">

PS. Sorry for my English skill 😅

**Comment by AppDevGuy** [comment] 2020-10-08 07:21
Thanks for sending through the screenshot of the crash. The issue is not your fault. 

Could you please confirm for me which version of OSSSpeechKit you are using? I resolved this issue recently however I am unsure if it is in 0.3.2 or beta version 0.4.0 which is not yet available.

**Comment by jameszasod** [comment] 2020-10-08 07:25
My version is 0.3.2.

**Comment by AppDevGuy** [comment] 2020-10-08 07:27
I have identified the issue is in v0.3.2. The issue has been resolved in beta version 0.4.0. 

To get around this issue urgently, you are welcome to use version 0.4.0 by implementing:

```
pod 'OSSSpeechKit', , :git => 'https://github.com/AppDevGuy/OSSSpeechKit.git', :branch => 'v0.4.0_develop'
```

### Caution though - is a development branch and changes may occur in future development that may break your code. 

It's unlikely that I will release a patch for this issue in this version. Version 0.4.0 should be available for full release soon.

**Comment by jameszasod** [comment] 2020-10-08 07:37
I can't update pod.
sorry I'm a beginner
<img width="489" alt="Screen Shot 2563-10-08 at 14 36 21" src="https://user-images.githubusercontent.com/13145084/95428845-c4a57980-0973-11eb-9485-d5a3b9cb8763.png">

**Comment by AppDevGuy** [comment] 2020-10-08 07:43
Could you please share the code from your Podfile? 

Some steps to help:

```
rm -rf Podfile.lock
rm -rf Pods
pod install
```

First line removes the Podfile lock file. 

Second line removes your projects Pods.

Third line installs them all again.

**Comment by jameszasod** [comment] 2020-10-08 07:47
Sure.

platform :ios, '12.0'
target 'SpeechSiwa' do
  use_frameworks!

  #pod 'OSSSpeechKit'
  pod 'OSSSpeechKit', :git => 'https://github.com/AppDevGuy/OSSSpeechKit.git', :branch => 'v0.4.0_develop'
  
end

**Comment by AppDevGuy** [comment] 2020-10-08 07:51
Great, thanks. 

At the top of your Podfile, add this line:

```
source 'https://cdn.cocoapods.org/'
```

Your file should look like this:

```
source 'https://cdn.cocoapods.org/'

platform :ios, '12.0'
target 'SpeechSiwa' do
use_frameworks!

#pod 'OSSSpeechKit'
pod 'OSSSpeechKit', :git => 'https://github.com/AppDevGuy/OSSSpeechKit.git', :branch => 'v0.4.0_develop'

end
```

The only concern I have is that iOS 13 is the minimum supported version for all new apps, which the 0.4.0 Podspec also uses. Consider updating `platform :ios, '12.0'` to `platform :ios, '13.0'`.

If you have any further issues I will see what I can do later in the day.

**Comment by jameszasod** [comment] 2020-10-08 07:56
It's the same problem sir, I can't install pod 😢

**Comment by AppDevGuy** [comment] 2020-10-08 07:59
As a temporary solution, edit the OSSpeechKit file (it might ask you to unlock it - select yes/ok/continue) and change the lines that crash from:

```
        if let engine = audioEngine {
            if engine.isRunning {
                cancelRecording()
            }
        } else {
            audioEngine = AVAudioEngine()
        }
```

to be:

```
        if let engine = audioEngine {
            if engine.isRunning {
                cancelRecording()
            }
        }
        audioEngine = AVAudioEngine()
```

That will fix the issue. Once v0.4.0 is release the issue will be resolved.

**Comment by jameszasod** [comment] 2020-10-08 08:03
It's work!! 🤩
Thank you so much ☺️

**Comment by AppDevGuy** [comment] 2020-10-08 08:05
Great. Just remember, each time you update your pods, those changes will be blown away so you may have to add them again. Once v0.4.0 is available you won't have the issue any more.

**Closed** 2020-10-08 08:06 UTC
Labels: bug, v0.3, wontfix

**Comment by jameszasod** [comment] 2020-10-08 08:11
Please let me know when v0.4.0 is release.
Thank! 🥳
